# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [commit]
repos:
  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: "v0.3.1"
    hooks:
      - id: absolufy-imports

  - repo: https://github.com/ambv/black
    rev: "22.3.0"
    hooks:
      - id: black
        language_version: python3.9

  - repo: https://github.com/gvanderest/pylama-pre-commit
    rev: 0.1.2
    hooks:
      - id: pylama

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v3.4.0"
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-ast
      - id: check-added-large-files
      - id: check-merge-conflict
        args:
          - "--assume-in-merge"
      - id: check-json
      - id: pretty-format-json
        args:
          - "--autofix"
          - "--no-sort-keys"
          - "--no-ensure-ascii"


  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: "v1.2.4"
    hooks:
      - id: python-safety-dependencies-check
        files: pyproject.toml

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: "v1.8.0"
    hooks:
      - id: python-no-log-warn
      - id: python-check-mock-methods
      - id: python-no-eval

  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.0"
    hooks:
      - id: bandit
        files: "^src/.*"

  - repo: https://github.com/codespell-project/codespell
    rev: "v2.1.0"
    hooks:
      - id: codespell
        args: ["-w"]
